name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gavin
            asset_name: gavin-linux-amd64
          - os: windows-latest
            artifact_name: gavin.exe
            asset_name: gavin-windows-amd64.exe
          - os: macos-latest
            artifact_name: gavin
            asset_name: gavin-macos-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.artifact_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
